# Generated by Django 5.2 on 2025-05-05 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('institution', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('link', models.URLField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('current', models.BooleanField(default=False)),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Maria Eduarda Oliveira Galdino', max_length=200)),
                ('photo', models.ImageField(upload_to='profile_photos/')),
                ('bio', models.TextField(default='Prazer, eu me chamo Maria Eduarda, curso ciencia da computacao no insper e tenho entusiasmo por programação e desejo crescer profissionalmente no setor de tecnologia.')),
                ('email', models.EmailField(default='meog38@gmail.com', max_length=254)),
                ('phone', models.CharField(default='28999049728', max_length=20)),
                ('github', models.URLField(default='https://github.com/Meog38')),
                ('linkedin', models.URLField(default='https://www.linkedin.com/in/meog38/')),
            ],
            options={
                'verbose_name_plural': 'Profile',
            },
        ),
    ]
